### ISSUE TITLE
Date casting (format issue) into MongoDB

### ISSUE THREAD

**Issue by trnigg** [trnigg/friend-commends#2]
## Issue
When attempting to create a new user with DOBin Australian format (e.g. 26/10/1994), following error is returned in Apollo client:
```
"message": "User validation failed: dateOfBirth: Cast to date failed for value \"26/10/1994\" (type string) at path \"dateOfBirth\"",
```

Note, mutation currently takes string, and model in MongoDB handles conversion using JavaScript Date.
Using US, month-first format currently works.

## Solution
Either fix on front-end after query, or resolve back? For now, with development simply using US date format (ie 10/26/1994)

**Comment by trnigg** [comment]
My apologies, I hadn't fully investigated it, it was just something I ran into while working on something else and didn't want to forget!

**Comment by amethystlyre** [comment]
Not at all,
Yep I ran into it before I saw your comment here lol, i don't seem to get notifications for issues lol

> My apologies, I hadn't fully investigated it, it was just something I ran into while working on something else and didn't want to forget!
